// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKegJAXKS3OpAjTO14DrOcDOOokXXWOtA',
    appId: '1:825208118320:web:9f94ea05ed3c210d2b21f5',
    messagingSenderId: '825208118320',
    projectId: 'flipkart-clone-1',
    authDomain: 'flipkart-clone-1.firebaseapp.com',
    storageBucket: 'flipkart-clone-1.appspot.com',
    measurementId: 'G-8Z8SGHP4GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsHCaAEuxNN8HO27ro43H9H9wGXpbJQg',
    appId: '1:825208118320:android:453beeb6daaf04562b21f5',
    messagingSenderId: '825208118320',
    projectId: 'flipkart-clone-1',
    storageBucket: 'flipkart-clone-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBbHlc5q1SoDtu1DcNEQ6joupyVl0zk8',
    appId: '1:825208118320:ios:2166687f8487fca52b21f5',
    messagingSenderId: '825208118320',
    projectId: 'flipkart-clone-1',
    storageBucket: 'flipkart-clone-1.appspot.com',
    iosBundleId: 'com.myrik.flipkartClone',
  );
}
